<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Xa Backup Schedules</name>
   <tag></tag>
   <elementGuidId>8d934568-4212-492d-a770-77abb60f88d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.el-dropdown-menu__item.bf-dropdown-item.border-top-solid.border-width-top-1.border-top-gray-200 > span.text-red</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='dropdown-menu-306']/li[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0adbdab9-194f-4b53-8d2e-71c454de3996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-red</value>
      <webElementGuid>e609b4ea-4392-482b-aabd-59ad0658a66c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Xóa Backup Schedules</value>
      <webElementGuid>6bbbb305-aaf8-489f-a70b-359150be997d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdown-menu-306&quot;)/li[@class=&quot;el-dropdown-menu__item bf-dropdown-item border-top-solid border-width-top-1 border-top-gray-200&quot;]/span[@class=&quot;text-red&quot;]</value>
      <webElementGuid>3d979d4b-12d0-49e3-9d67-369993db6cac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='dropdown-menu-306']/li[2]/span</value>
      <webElementGuid>3ffc6155-02a9-480b-953d-0261680638a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chi tiết'])[1]/following::span[1]</value>
      <webElementGuid>2dba5e91-0f27-43b4-bc30-6e7661462a0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::span[2]</value>
      <webElementGuid>f4a33ed0-4702-4758-891b-2b69c8d16031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Xóa Backup Schedules']/parent::*</value>
      <webElementGuid>53267fca-ab38-4fb1-bca8-f8ebe61a2d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/ul/li[2]/span</value>
      <webElementGuid>cac78786-4735-44d5-ae05-3a8f3e4278f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Xóa Backup Schedules' or . = 'Xóa Backup Schedules')]</value>
      <webElementGuid>d5ab6ee7-d2c2-4ab3-be1f-c093a7401b75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
