<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Xa</name>
   <tag></tag>
   <elementGuidId>073fd9a7-5c9c-4909-bb26-58e706beb32c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='/instance/79d48d74-c97b-4ffe-a3c4-d59e5ec824ca/delete']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>f30e077a-cf8c-4cf1-b5d0-deb87ea66b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>049a5e91-fe83-48c3-8d56-40e75173b6e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>aa370d0d-ed18-4cf8-b2c0-e972b967bc1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-menu-item is-active</value>
      <webElementGuid>f2c2cc10-4644-4c1c-b4ad-d1e7d052a094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>/instance/79d48d74-c97b-4ffe-a3c4-d59e5ec824ca/delete</value>
      <webElementGuid>d35e54f1-222a-4ca4-a8ee-7d74e5e2feb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          Xóa
          </value>
      <webElementGuid>5e8a150d-53f6-4b1c-ab23-ea264b9978b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;/instance/79d48d74-c97b-4ffe-a3c4-d59e5ec824ca/delete&quot;)</value>
      <webElementGuid>d79e2aa6-3ba9-4812-b125-e7b29c47c783</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='/instance/79d48d74-c97b-4ffe-a3c4-d59e5ec824ca/delete']</value>
      <webElementGuid>64adfb7a-1b20-43d1-90f8-adb05dc4843b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/ul/li[5]</value>
      <webElementGuid>e9b3efd1-66c5-4dc5-9046-c4b614a7730b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cài đặt'])[1]/following::li[1]</value>
      <webElementGuid>5af3b18c-4154-4db6-bd5e-8672e7ab63fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nodes'])[1]/following::li[2]</value>
      <webElementGuid>d42d36d6-a0e8-4dc5-a034-ce468ec0eaa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Database Engine:'])[1]/preceding::li[1]</value>
      <webElementGuid>8cafc2ab-028f-4873-85ff-24d3b2b7d026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[5]</value>
      <webElementGuid>bc261a5b-26b7-4018-b30d-e8eae03aaee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '/instance/79d48d74-c97b-4ffe-a3c4-d59e5ec824ca/delete' and (text() = '
          Xóa
          ' or . = '
          Xóa
          ')]</value>
      <webElementGuid>dc6dddc2-097e-485c-8381-70e209ee907a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
