<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_HN1</name>
   <tag></tag>
   <elementGuidId>ba7794af-312e-437f-a9cf-debd645d48fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/label[2]/span[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8bfc32e2-14b3-44b5-bc62-fbfe94cf5f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-row is-align-middle el-row--flex</value>
      <webElementGuid>33cf5a4e-fa3d-40f9-ada6-4ca5b989495f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
          HN1
        </value>
      <webElementGuid>023093c2-6076-4a8e-9ecb-6734595f4133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:@bizfly/cloud-database&quot;)/div[@id=&quot;app&quot;]/div[@class=&quot;project-create-layout&quot;]/div[@class=&quot;router-view&quot;]/div[1]/div[@class=&quot;el-card is-never-shadow border in&quot;]/div[@class=&quot;el-card__body&quot;]/div[@class=&quot;el-card__content p-m&quot;]/div[1]/div[1]/div[@class=&quot;el-card mb-m is-never-shadow in&quot;]/div[@class=&quot;el-card__body&quot;]/div[@class=&quot;el-card__content&quot;]/div[1]/div[1]/div[@class=&quot;el-radio-group w-100&quot;]/div[@class=&quot;select-region&quot;]/label[@class=&quot;el-radio w-100 p-m mr-xs is-bordered label-xs hide-checker&quot;]/span[@class=&quot;el-radio__label&quot;]/div[@class=&quot;el-row is-align-middle el-row--flex&quot;]</value>
      <webElementGuid>e30ad82c-6a75-4a4f-9707-a24730adfc1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/label[2]/span[2]/div</value>
      <webElementGuid>b274cbba-464c-4b41-8cdf-1452f04fcb15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HN2'])[1]/following::div[1]</value>
      <webElementGuid>f6d9ab03-f77a-4ff6-b06f-7b89a22d7658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[14]</value>
      <webElementGuid>700393ae-bd2b-4752-b297-2bf138bed258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chọn Data center'])[2]/preceding::div[2]</value>
      <webElementGuid>26de6218-8988-44da-87b6-d87310957585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span[2]/div</value>
      <webElementGuid>1221ede0-a3d7-432b-8dd2-cc2be75e217f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' 
          HN1
        ' or . = ' 
          HN1
        ')]</value>
      <webElementGuid>0167d5ad-77ea-4209-b50f-a98149cb2763</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
