<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Xc nhn thng tin khi to</name>
   <tag></tag>
   <elementGuidId>32cf9cd1-bcd8-4039-b061-18d63e9f365a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.el-button.bf-button.w-100.el-button--primary.el-button--default</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>163a0254-d043-4b7a-9b3f-f4bdf71b58eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d25b40af-c885-4511-a90d-fb91fac3103a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-button bf-button w-100 el-button--primary el-button--default</value>
      <webElementGuid>7e8682e1-b10d-4526-8ce3-f098e78a3d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Xác nhận thông tin khởi tạo </value>
      <webElementGuid>e17d7bf9-ea0a-403b-8cbc-64335ac7eb0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:@bizfly/cloud-database&quot;)/div[@id=&quot;app&quot;]/div[@class=&quot;project-create-layout&quot;]/div[@class=&quot;router-view&quot;]/div[1]/div[@class=&quot;el-card resource-price is-never-shadow border in fixed-price&quot;]/div[@class=&quot;el-card__body&quot;]/div[@class=&quot;el-card__footer&quot;]/div[1]/div[@class=&quot;mb-l mx-m&quot;]/button[@class=&quot;el-button bf-button w-100 el-button--primary el-button--default&quot;]</value>
      <webElementGuid>7094e064-f3a0-46f9-8abf-8c04ce68001a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>f78c9c53-17fc-49dc-8795-176154de85ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/div[10]/div[2]/div[2]/div/div[2]/button</value>
      <webElementGuid>8e24b62a-18d8-4276-bc80-40aae788fc87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DUNG LƯỢNG LƯU TRỮ'])[1]/following::button[1]</value>
      <webElementGuid>8a019380-ae58-4942-af98-c2afb253bdae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VCPU / RAM'])[1]/following::button[1]</value>
      <webElementGuid>0393cc8f-cec2-432b-a1d7-de0549d48f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/button</value>
      <webElementGuid>e4686132-eeda-4736-9641-f50c4d5658d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Xác nhận thông tin khởi tạo ' or . = ' Xác nhận thông tin khởi tạo ')]</value>
      <webElementGuid>9f5ded0a-a863-4bc8-89c1-dd85af04bac3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
