<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_HN1</name>
   <tag></tag>
   <elementGuidId>e547cf56-2700-4b8d-a917-331a4df35d52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div/div[6]/div[2]/div/div/div/div/div/label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>843da6e7-d904-4477-9b38-b9a8a91abc56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4af2ea10-e4ea-4f5f-9e3d-7edbd458d205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>524bbf80-1aee-4b3f-907e-8abad783ffe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-radio w-100 p-m mr-xs is-bordered label-xs hide-checker</value>
      <webElementGuid>9022a585-ecfd-4f8e-949f-3545f0a7e0e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>labelsize</name>
      <type>Main</type>
      <value>xs</value>
      <webElementGuid>4be3f090-4220-447c-886d-7ebf61f1b8d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
          HN1
        </value>
      <webElementGuid>6c607436-88be-4565-8540-a13fe1e43678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:@bizfly/cloud-database&quot;)/div[@id=&quot;app&quot;]/div[@class=&quot;project-create-layout&quot;]/div[@class=&quot;router-view&quot;]/div[1]/div[@class=&quot;el-card is-never-shadow border in mb-l&quot;]/div[@class=&quot;el-card__body&quot;]/div[@class=&quot;el-card__content p-m&quot;]/div[1]/div[1]/div[@class=&quot;el-radio-group w-100&quot;]/div[@class=&quot;select-region&quot;]/label[@class=&quot;el-radio w-100 p-m mr-xs is-bordered label-xs hide-checker&quot;]</value>
      <webElementGuid>b50cce8c-5a96-4a9b-ba9f-d7aa06bba3f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/div[6]/div[2]/div/div/div/div/div/label[2]</value>
      <webElementGuid>49ccd7b3-a121-42c6-bfd3-e48a269f6bbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HN2'])[1]/following::label[1]</value>
      <webElementGuid>950fee78-af89-4bbd-9c6a-be00f6e460a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::label[2]</value>
      <webElementGuid>227efeed-cdcf-4ad2-ab47-f719544c5043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]</value>
      <webElementGuid>3563eda8-ce43-4c4d-a19c-3c92e94c997e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = ' 
          HN1
        ' or . = ' 
          HN1
        ')]</value>
      <webElementGuid>abddb0ae-3621-4393-bf67-07b4ab7aa5b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
