<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>small_MongoDB</name>
   <tag></tag>
   <elementGuidId>578ad2db-afd6-4f9a-9b20-2fdcccfdacc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pane-engine']/div/div[3]/div/div/div/small</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>small.el-tooltip.text-limit.text-medium.text-black.focusing</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>8d9d55d4-3115-4653-b0d6-cbd88157b2fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-tooltip text-limit text-medium text-black focusing</value>
      <webElementGuid>84c512b6-5673-4f4e-b016-5b636323b503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>el-tooltip-9577</value>
      <webElementGuid>3927cf48-ff73-4b0f-b153-7795f052138f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d9f48caa-35b2-44e0-8f29-4b7d858db673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            MongoDB
          </value>
      <webElementGuid>4fa6f2fe-83b7-4dd3-ab1a-e68e6a7ca7df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pane-engine&quot;)/div[@class=&quot;select-database-engine el-row el-row--flex&quot;]/div[@class=&quot;mr-xs cursor-pointer&quot;]/div[@class=&quot;el-tooltip border-radius-2xs border-solid border-gray-200 border-width-1&quot;]/div[@class=&quot;border-top-left-radius-2xs
        border-top-right-radius-2xs
        border-bottom-solid
        text-center
        p-m
       border-gray-200 border-width-bottom-1 border-bottom-solid border-width-bottom-1&quot;]/div[@class=&quot;el-row is-justify-center is-align-middle el-row--flex&quot;]/small[@class=&quot;el-tooltip text-limit text-medium text-black focusing&quot;]</value>
      <webElementGuid>333d7376-23d6-4d67-b40c-a0b4ed35565f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pane-engine']/div/div[3]/div/div/div/small</value>
      <webElementGuid>5261cc5e-d7c6-4173-99ee-cdd82a4e9e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chọn phiên bản'])[2]/following::small[1]</value>
      <webElementGuid>626246b8-efa3-4db7-8d2a-a000369cd18a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Redis'])[1]/following::small[1]</value>
      <webElementGuid>e64d927b-ed72-4400-b5f5-4744a4898e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chọn phiên bản'])[4]/preceding::small[1]</value>
      <webElementGuid>51935019-1a5d-40d2-a33d-f93b960e37ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='của 1'])[1]/preceding::small[1]</value>
      <webElementGuid>af7d9f69-4c13-416c-ba8d-c5430f379ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MongoDB']/parent::*</value>
      <webElementGuid>bffa62d9-54e5-45c2-ae32-e4c9b6052134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/small</value>
      <webElementGuid>742670a8-4651-4336-a6f5-0d264f4bc019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//small[(text() = '
            MongoDB
          ' or . = '
            MongoDB
          ')]</value>
      <webElementGuid>676409bd-c357-495b-8fd5-57f28131216b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
