<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>small_HN1</name>
   <tag></tag>
   <elementGuidId>6cbb17f3-f418-4753-b0ba-d7e9a91c3978</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div/div[6]/div[2]/div/div/div/div/div/label[2]/span[2]/div/small</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>e2cfd57e-e243-4b96-b6e3-6e4979084d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-medium</value>
      <webElementGuid>8e18461e-a6ea-41be-96fe-537574013dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          HN1
        </value>
      <webElementGuid>6c906905-a8e9-49d0-9755-1fb166dd0c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:@bizfly/cloud-database&quot;)/div[@id=&quot;app&quot;]/div[@class=&quot;project-create-layout&quot;]/div[@class=&quot;router-view px-xl mr-280&quot;]/div[1]/div[@class=&quot;el-card is-never-shadow border in mb-l&quot;]/div[@class=&quot;el-card__body&quot;]/div[@class=&quot;el-card__content p-m&quot;]/div[1]/div[1]/div[@class=&quot;el-radio-group w-100&quot;]/div[@class=&quot;select-region&quot;]/label[@class=&quot;el-radio w-100 p-m mr-xs is-bordered label-xs hide-checker&quot;]/span[@class=&quot;el-radio__label&quot;]/div[@class=&quot;el-row is-align-middle el-row--flex&quot;]/small[@class=&quot;text-medium&quot;]</value>
      <webElementGuid>f17c7930-4c40-4165-aa72-8804ecaad333</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/div[6]/div[2]/div/div/div/div/div/label[2]/span[2]/div/small</value>
      <webElementGuid>eed8a17f-0a2b-4f02-b052-b60fef2f31ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HN2'])[1]/following::small[1]</value>
      <webElementGuid>d892ff4f-4817-4464-aab6-1f302acfdb53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::small[2]</value>
      <webElementGuid>a4ce4edc-23f5-4837-b32d-732a8eaf2ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/preceding::small[1]</value>
      <webElementGuid>3a119f2f-75f8-465f-bcdc-78dc22e78884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='HN1']/parent::*</value>
      <webElementGuid>d84ccda7-217f-46ff-8113-d7b3c8a07c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span[2]/div/small</value>
      <webElementGuid>c1cb451c-c251-4499-8692-04086cc67c76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//small[(text() = '
          HN1
        ' or . = '
          HN1
        ')]</value>
      <webElementGuid>f128765d-164c-4a6f-a1f4-83a0f60912d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
