<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Xa</name>
   <tag></tag>
   <elementGuidId>45dbba5d-997f-424b-a501-5c8a6f1ded61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='dropdown-menu-1246']/li[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dropdown-menu-1246 > li.el-dropdown-menu__item.bf-dropdown-item.m-0.el-dropdown-menu__item--divided</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>d7fa9f75-f7fc-462b-ad24-5951f8f9dbe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c5b52982-d556-441b-8138-bd2a2e8dab7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-dropdown-menu__item bf-dropdown-item m-0 el-dropdown-menu__item--divided</value>
      <webElementGuid>9c972cf2-f0c9-477b-88e0-3a70327e8a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Xóa</value>
      <webElementGuid>0d716ded-e4b4-4801-a7e0-171f93207369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdown-menu-1246&quot;)/li[@class=&quot;el-dropdown-menu__item bf-dropdown-item m-0 el-dropdown-menu__item--divided&quot;]</value>
      <webElementGuid>54fa2b90-c0a7-42bc-991a-7fb517f360e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='dropdown-menu-1246']/li[2]</value>
      <webElementGuid>4b2c9edd-27d8-430c-9c80-d02f19355516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tạo Database Instances'])[5]/following::li[1]</value>
      <webElementGuid>ce032941-05fc-4f72-b11a-fa8e9276ecb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::li[2]</value>
      <webElementGuid>54dfc94d-315b-42bc-a012-f4874a65b77e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/ul/li[2]</value>
      <webElementGuid>1b1e878a-8378-49e9-862d-5712c5a0683f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Xóa' or . = 'Xóa')]</value>
      <webElementGuid>266f6d87-1c71-4410-b0c9-773725398e23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
