<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Xa</name>
   <tag></tag>
   <elementGuidId>2764628a-ce2e-4243-90c8-257e2a724d41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.el-dropdown-menu__item.bf-dropdown-item.border-top-solid.border-width-top-1.border-top-gray-200</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='dropdown-menu-1180']/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>4719f8d0-4835-4c49-b61a-63804815a720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>2232ec2f-a10f-4145-85df-636efcc73bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-dropdown-menu__item bf-dropdown-item border-top-solid border-width-top-1 border-top-gray-200</value>
      <webElementGuid>1d5c2148-2949-40f8-b312-482da30d3d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Xóa</value>
      <webElementGuid>57be738b-eac5-4f35-98a0-1f8437803698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdown-menu-1180&quot;)/li[@class=&quot;el-dropdown-menu__item bf-dropdown-item border-top-solid border-width-top-1 border-top-gray-200&quot;]</value>
      <webElementGuid>2a10dcf3-a26d-463c-ac79-2fe7e35f4dec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='dropdown-menu-1180']/li[2]</value>
      <webElementGuid>21965718-aa2d-4333-b4c0-4babaa0af316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cập nhật'])[1]/following::li[1]</value>
      <webElementGuid>392652e3-8818-4c03-b551-9fa80f2440b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::li[2]</value>
      <webElementGuid>c91cd186-095e-42a4-918d-fc7e066eef8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/ul/li[2]</value>
      <webElementGuid>7ef59a52-04b5-4aca-9cfe-362b763ab70f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Xóa' or . = 'Xóa')]</value>
      <webElementGuid>bd4de8bb-e7f0-4e6d-bacd-4fe36e6d62cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
