<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Thay i cu hnh</name>
   <tag></tag>
   <elementGuidId>9724d9d1-2984-43d1-944a-5b1a91e871d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.el-tooltip.focusing</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div/div[3]/div[2]/button/span/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>54c8cf10-62a1-4823-9e15-7c9dd6f14c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-tooltip focusing</value>
      <webElementGuid>2015f7d0-5e8d-45a7-bca1-4e2545187f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>el-tooltip-5791</value>
      <webElementGuid>29b8cd03-ead4-49a6-92e6-6d3cf3752e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d6ca328b-4d85-4a0c-81e5-84af094ec863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Thay đổi cấu hình </value>
      <webElementGuid>22852ffd-5936-4d62-8a4f-4996935f8a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:@bizfly/cloud-database&quot;)/div[@id=&quot;app&quot;]/div[@class=&quot;node-detail-layout&quot;]/div[@class=&quot;router-view&quot;]/div[1]/div[3]/div[@class=&quot;pt-m el-row is-justify-end el-row--flex&quot;]/button[@class=&quot;el-button bf-button el-button--primary el-button--default&quot;]/span[1]/div[@class=&quot;button-content&quot;]/span[@class=&quot;el-tooltip focusing&quot;]</value>
      <webElementGuid>600b3671-2f79-4c4b-b1a6-24e0e7f6c50f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/div[3]/div[2]/button/span/div/span</value>
      <webElementGuid>b31129cf-48dc-4883-b954-f5d0ca5ef985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MongoDB - 4.4.7'])[2]/following::span[2]</value>
      <webElementGuid>2f0db022-671f-44ef-818b-b950ad0c3a40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cấu hình mới'])[1]/following::span[4]</value>
      <webElementGuid>67c0f316-4736-4f9e-854a-a5bf1d2e1862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tài liệu hướng dẫn'])[1]/preceding::span[1]</value>
      <webElementGuid>838440b0-2b2a-4446-8fa4-e52145aca558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::span[1]</value>
      <webElementGuid>e808d287-7ab2-4775-943c-11f55727577b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/span/div/span</value>
      <webElementGuid>5b60a1f6-f37f-4013-a9dd-729ffbf1a4fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Thay đổi cấu hình ' or . = ' Thay đổi cấu hình ')]</value>
      <webElementGuid>1bb6f7af-0002-452b-ae2a-d8ffa36db390</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
