<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_mmmmmmmmm</name>
   <tag></tag>
   <elementGuidId>d0f6702d-f1e5-44b5-82e8-f35c4cb5d830</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[3]/table/tbody/tr/td/div/div/a/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.el-row.el-row--flex > p.text-limit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d9540e7e-08fa-4394-a6a7-bea6f185ff49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-limit</value>
      <webElementGuid>a6b8aecc-1e40-424e-b223-34bb9122e67b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mmmmmmmmm</value>
      <webElementGuid>508a4c85-c9c7-4c2b-b505-84620f2eaf18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:@bizfly/cloud-database&quot;)/div[@id=&quot;app&quot;]/div[@class=&quot;list-layout&quot;]/div[@class=&quot;router-view&quot;]/div[@class=&quot;instances&quot;]/div[@class=&quot;el-card is-never-shadow border in&quot;]/div[@class=&quot;el-card__body&quot;]/div[@class=&quot;el-card__content p-0&quot;]/div[1]/div[@class=&quot;content-slot pt-m&quot;]/div[@class=&quot;el-table el-table--fit el-table--scrollable-x el-table--enable-row-hover el-table--enable-row-transition bf-table-action&quot;]/div[@class=&quot;el-table__body-wrapper is-scrolling-left&quot;]/table[@class=&quot;el-table__body&quot;]/tbody[1]/tr[@class=&quot;el-table__row&quot;]/td[@class=&quot;el-table_1_column_1&quot;]/div[@class=&quot;cell&quot;]/div[@class=&quot;bf-link el-tooltip bf-link--default&quot;]/a[@class=&quot;text-limit&quot;]/div[@class=&quot;el-row el-row--flex&quot;]/p[@class=&quot;text-limit&quot;]</value>
      <webElementGuid>a7aa7464-13f9-48d8-90d5-5ea82e7fd6a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[3]/table/tbody/tr/td/div/div/a/div/p</value>
      <webElementGuid>3add28ae-b6ce-4df8-a279-45e884e1faf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thời gian'])[1]/following::p[1]</value>
      <webElementGuid>f1f3f36e-83f3-4e41-8fe0-ee0e6a7ae9b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trạng thái'])[1]/following::p[1]</value>
      <webElementGuid>60ed2680-d630-4311-866a-86143e7a2991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Không'])[1]/preceding::p[2]</value>
      <webElementGuid>e59e3488-8ed0-4499-b1d4-afd7c050a05e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACTIVE'])[1]/preceding::p[2]</value>
      <webElementGuid>60d1f3ec-3446-4cfe-95a2-e0be7b53f82a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='mmmmmmmmm']/parent::*</value>
      <webElementGuid>b8309ccf-0237-4352-832f-2ab7d729d59f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/a/div/p</value>
      <webElementGuid>b4160d97-8bbf-4288-863b-6e23a3be7695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'mmmmmmmmm' or . = 'mmmmmmmmm')]</value>
      <webElementGuid>40f84491-a9c2-46f1-9b7b-ad546fac4bb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
