<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Xa</name>
   <tag></tag>
   <elementGuidId>7946059e-47f1-4726-9e47-d1960de53bf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='/instance/f61e41a5-5202-46ae-b6a4-b46c21c4b7d3/delete']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>1a614f7f-c7a1-43a7-b22b-7ede9eea7078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>13493fe0-647f-4b68-b7eb-7f7a67d29965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>8165e429-d526-4428-9d95-ada03d322ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-menu-item</value>
      <webElementGuid>30cd0b76-e05d-421c-9a39-6696a5ef1053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>/instance/f61e41a5-5202-46ae-b6a4-b46c21c4b7d3/delete</value>
      <webElementGuid>f9dc1bb1-f099-4b3c-9056-d20f92a1820d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Xóa  </value>
      <webElementGuid>1590b88a-3145-4e22-873a-d37c5464e0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;/instance/f61e41a5-5202-46ae-b6a4-b46c21c4b7d3/delete&quot;)</value>
      <webElementGuid>c9fcfa64-0e66-4e4d-9d8a-29c979876f65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='/instance/f61e41a5-5202-46ae-b6a4-b46c21c4b7d3/delete']</value>
      <webElementGuid>4fd3c143-cb30-4bca-be54-e81da60e0c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/ul/li[5]</value>
      <webElementGuid>d68ab0d6-6bd2-4ca3-838b-82cd6595c3c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>'])[3]/following::li[5]</value>
      <webElementGuid>6055b9c5-2528-42b3-8340-07c759db72bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dTi0V'])[1]/following::li[5]</value>
      <webElementGuid>a791ce09-5f29-453a-b94f-a7d70245cded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dTi0V'])[2]/preceding::li[1]</value>
      <webElementGuid>d7c06e2b-4493-4411-9964-ea9de361bd04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Database Engine:'])[1]/preceding::li[1]</value>
      <webElementGuid>85565ab4-69d8-4790-8308-6c381ae84d7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[5]</value>
      <webElementGuid>e2ec68e6-067f-4a07-9060-c6cc9218f0be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '/instance/f61e41a5-5202-46ae-b6a4-b46c21c4b7d3/delete' and (text() = 'Xóa  ' or . = 'Xóa  ')]</value>
      <webElementGuid>2afac265-8709-4ea1-aa92-18225e7e1d88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
