<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Chn pht_el-input__inner</name>
   <tag></tag>
   <elementGuidId>626192cd-6efb-4475-aecf-3a299453cf86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.el-col.el-col-6.el-col-offset-0.el-col-pull-0.el-col-push-0.el-col-mobile-24.el-col-large-tablet-12 > div.el-form-item.mb-0.is-required > div.el-form-item__content > div.el-select.bf-select.w-100.selectSize > div.el-input.el-input--suffix > input.el-input__inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d697b603-0761-4d3d-9fff-46d5aed06b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ec4c1208-f4bb-41ef-adff-bcad7e7c446a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>7010854f-e361-453c-8515-73bc33e50337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a0f58a00-66ea-49fb-b745-f2691f87a2b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Chọn</value>
      <webElementGuid>dbacc0c7-1021-4b8e-bc20-99fdab60bf3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__inner</value>
      <webElementGuid>9c08fe49-95a7-43d2-8f5b-1e087e57d594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:@bizfly/cloud-database&quot;)/div[@id=&quot;app&quot;]/div[@class=&quot;list-layout&quot;]/div[@class=&quot;router-view&quot;]/div[2]/div[@class=&quot;el-card is-never-shadow border in mb-l&quot;]/div[@class=&quot;el-card__body&quot;]/div[@class=&quot;el-card__content p-m&quot;]/div[1]/div[1]/div[@class=&quot;mt-m el-row is-align-middle el-row--flex&quot;]/form[@class=&quot;el-form w-100&quot;]/div[@class=&quot;el-row&quot;]/div[@class=&quot;el-col el-col-6 el-col-offset-0 el-col-pull-0 el-col-push-0  el-col-mobile-24 el-col-large-tablet-12&quot;]/div[@class=&quot;el-form-item mb-0 is-required&quot;]/div[@class=&quot;el-form-item__content&quot;]/div[@class=&quot;el-select bf-select w-100 selectSize&quot;]/div[@class=&quot;el-input el-input--suffix&quot;]/input[@class=&quot;el-input__inner&quot;]</value>
      <webElementGuid>8b9067ba-df34-4add-adc4-3508a58a6c4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[6]</value>
      <webElementGuid>86fb4ac1-5e05-4722-9d36-aa38b316d7b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div[4]/div[2]/div/div/div/div/form/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>422df9d4-e733-4811-8618-20609f0f754a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>16ab7007-1122-4f03-a082-a63f3df93028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Chọn']</value>
      <webElementGuid>82dd119d-6fa5-48eb-a212-90f37c1c3081</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
