<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Xc nhn</name>
   <tag></tag>
   <elementGuidId>62875dc5-4526-4c13-85cd-19ba2dd696ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mt-m.pt-m.pl-m.pr-0.bg-white.text-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div/div[2]/div/div[2]/div/div/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7a7e6695-cdae-4c37-b84c-af58d1789f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-m pt-m pl-m pr-0 bg-white text-right</value>
      <webElementGuid>cc1a5faa-0506-4a73-acc2-affe0f706d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Xác nhận </value>
      <webElementGuid>83590d3f-9bcd-4f30-8637-825e426b77b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:@bizfly/cloud-database&quot;)/div[@id=&quot;app&quot;]/div[@class=&quot;backup-schedule-layout&quot;]/div[@class=&quot;router-view&quot;]/div[1]/div[2]/div[@class=&quot;el-card is-never-shadow border in&quot;]/div[@class=&quot;el-card__body&quot;]/div[@class=&quot;el-card__content p-m&quot;]/div[1]/div[1]/div[@class=&quot;mt-m pt-m pl-m pr-0 bg-white text-right&quot;]</value>
      <webElementGuid>bbc54a66-a782-4197-a544-17fd893dcbba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/div[2]/div/div[2]/div/div/div/div[3]</value>
      <webElementGuid>bb421137-4468-49cf-a0f7-6e667b5f8913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vui lòng nhập OK để xác nhận.'])[1]/following::div[1]</value>
      <webElementGuid>e4d04e8d-76e3-4512-aca3-a0083fc16a1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/following::div[11]</value>
      <webElementGuid>2479e972-1266-4570-a53e-e2cd4d13e2f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[2]</value>
      <webElementGuid>35a7b150-2f81-4225-b71e-e11fe0388847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[3]</value>
      <webElementGuid>43039359-c9f2-4f2f-bbc7-84408742ebf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Xác nhận ' or . = 'Xác nhận ')]</value>
      <webElementGuid>420ea168-ef79-417c-bccd-bd506a6b95df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
