<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OK_el-input__inner</name>
   <tag></tag>
   <elementGuidId>6dc82ff5-6895-4a9d-84fa-d5fd547a2682</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.bf-input.el-input > input.el-input__inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a127340c-9c84-4a91-87cd-0c6e2f780e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d4f28af7-01e0-451d-a01c-48b08ae21786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b35efe93-a5fd-4f1c-8492-3a6d94019b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Vui lòng nhập OK để xác nhận.</value>
      <webElementGuid>ac3a8f77-d6e6-4e1b-ad8c-160cd3964f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>1ffa2e8e-ae26-4d71-b77b-32e851d6c0ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__inner</value>
      <webElementGuid>eda09b56-a8a2-4268-a706-f7541cfbde86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:@bizfly/cloud-database&quot;)/div[@id=&quot;app&quot;]/div[@class=&quot;backup-layout&quot;]/div[@class=&quot;router-view&quot;]/div[1]/div[2]/div[@class=&quot;el-card mb-m is-never-shadow border in&quot;]/div[@class=&quot;el-card__body&quot;]/div[@class=&quot;el-card__content p-m&quot;]/div[1]/div[1]/form[@class=&quot;el-form&quot;]/div[@class=&quot;el-row is-justify-space-between is-align-middle el-row--flex&quot;]/div[@class=&quot;el-col el-col-12 el-col-offset-0 el-col-pull-0 el-col-push-0&quot;]/div[@class=&quot;el-form-item m-0 is-required&quot;]/div[@class=&quot;el-form-item__content&quot;]/div[@class=&quot;bf-input el-input&quot;]/input[@class=&quot;el-input__inner&quot;]</value>
      <webElementGuid>106ec92f-41ab-4a11-8588-bee041c9ce2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[2]</value>
      <webElementGuid>fb6fa06e-948e-4279-a105-d8e6f9a59010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/div[2]/div/div[2]/div/div/div/form/div/div[2]/div/div/div/input</value>
      <webElementGuid>1ddf76c3-512b-44b5-a06c-3ac447e193eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>2b59e9db-7e14-40da-8943-70922ae5ceac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Vui lòng nhập OK để xác nhận.']</value>
      <webElementGuid>e08259f1-2486-4c4e-9a58-602d011b2805</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
