<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__el-input__inner (1)</name>
   <tag></tag>
   <elementGuidId>a6940e73-1fdb-4361-9e45-e4e85a786b0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.bf-input.custom-volume-input.el-input > input.el-input__inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e085025-d36e-42bb-9930-716d9a095bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4977e42b-b8ef-4e8a-83cb-47d029ec2d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d65d1608-99c6-47b0-a89a-c5c5201270fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập giá trị</value>
      <webElementGuid>b459b552-463c-4e27-8a85-e4ccf8ce6d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>3f8cca9f-77c8-4d3b-870a-12a063e08626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__inner</value>
      <webElementGuid>bf61776a-c2a7-4566-800f-ce9b91290d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carousel_mriwbki765&quot;)/div[@class=&quot;owl-stage-outer&quot;]/div[@class=&quot;owl-stage&quot;]/div[@class=&quot;owl-item active&quot;]/div[@class=&quot;bf-carousel-item&quot;]/div[@class=&quot;el-tooltip border-radius-2xs border-solid cursor-pointer flavor-item border-primary lighten-50  border-width-2&quot;]/div[@class=&quot;border-width-top-1 border-top-solid border-gray-200 el-row el-row--flex&quot;]/div[@class=&quot;bf-input custom-volume-input el-input&quot;]/input[@class=&quot;el-input__inner&quot;]</value>
      <webElementGuid>6d317701-79e2-4a91-8779-dcf951728f3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='number']</value>
      <webElementGuid>db5abcac-62c4-4510-b2a2-1d140cd03dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='carousel_mriwbki765']/div/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>589cb838-18ec-4be0-85db-0dbd3a8ad7c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>32f5f36c-8326-4a36-a91b-21d426e3c048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = 'Nhập giá trị']</value>
      <webElementGuid>be4c456f-87e1-4926-b181-8a2c2098dc38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
