<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__el-input__inner - capacity of disk</name>
   <tag></tag>
   <elementGuidId>5e4cc16c-6cef-41d9-8bbf-616ca4b0a475</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.bf-input.custom-volume-input.el-input > input.el-input__inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>500b7610-55d3-4451-8b06-51d8204ec457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c1fbbcb9-3ec7-45fe-8e6a-4002c8a1bfe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>15cd1f46-fcc3-4071-9dcf-8e1fa8c71e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập giá trị</value>
      <webElementGuid>3e6e8a95-9969-44f2-b687-154e1d316d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>2854db4c-fc06-4e3c-ab61-512cdc39e535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__inner</value>
      <webElementGuid>e3b837e0-1b8c-4a96-a2f7-f232dbfa0c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carousel_mriwbki765&quot;)/div[@class=&quot;owl-stage-outer&quot;]/div[@class=&quot;owl-stage&quot;]/div[@class=&quot;owl-item active&quot;]/div[@class=&quot;bf-carousel-item&quot;]/div[@class=&quot;el-tooltip border-radius-2xs border-solid cursor-pointer flavor-item border-primary lighten-50  border-width-2&quot;]/div[@class=&quot;border-width-top-1 border-top-solid border-gray-200 el-row el-row--flex&quot;]/div[@class=&quot;bf-input custom-volume-input el-input&quot;]/input[@class=&quot;el-input__inner&quot;]</value>
      <webElementGuid>832f3585-2ec7-4dc3-a733-e0741b840dd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='number']</value>
      <webElementGuid>c832b46e-378f-4201-b49a-2949d25a4b03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='carousel_mriwbki765']/div/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>473b3bc6-d38b-4045-9e13-26f9eca87621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>fd238566-d5a4-4e4a-9d3b-c85ff67934ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = 'Nhập giá trị']</value>
      <webElementGuid>3de7cf7e-66f5-4246-9028-6f8567356a58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
