<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Backups</name>
   <tag></tag>
   <elementGuidId>8e74c6a8-5425-4aa8-b26c-088103785a2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab-backup</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab-backup']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>de62538b-5411-464b-8882-c14c08f2dd97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-backup</value>
      <webElementGuid>0dabc7c8-7c19-46e1-9514-be1d1a638625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pane-backup</value>
      <webElementGuid>6ae219e3-51f7-441e-be58-211dd370dee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>8ad3b43c-a0a8-4391-9282-bef7d3b116bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>01fb2110-e0f3-4da3-b496-1e6b9ba84f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-tabs__item is-top is-focus</value>
      <webElementGuid>47284edb-dfc9-407e-943e-37cc18d02ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Backups</value>
      <webElementGuid>0bfccc26-e850-4231-a5a4-a947f1051b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-backup&quot;)</value>
      <webElementGuid>1e2040fc-6f45-4c6d-811f-d91d5afceb12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tab-backup']</value>
      <webElementGuid>b039f559-4b27-4ed7-9bd1-be9a4d768325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/div[3]</value>
      <webElementGuid>3e477694-472f-4452-9ec0-b75efb24a8fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Database Engine'])[1]/following::div[1]</value>
      <webElementGuid>03f7d780-d2b8-48a3-8bee-a8f3a13a1d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[12]</value>
      <webElementGuid>5fc66729-b73d-49dc-b52e-44096323326c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MariaDB'])[1]/preceding::div[2]</value>
      <webElementGuid>5621f2c5-981d-412d-aaa4-bd43cc8bd970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Redis'])[1]/preceding::div[13]</value>
      <webElementGuid>b133ed06-ed79-493f-90fc-58d783978dd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Backups']/parent::*</value>
      <webElementGuid>7f5b20dd-70f0-4676-bd2a-c1aeb8484f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/div[3]</value>
      <webElementGuid>63e6def3-0de4-4486-b44c-a9ed1027173d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tab-backup' and (text() = 'Backups' or . = 'Backups')]</value>
      <webElementGuid>faae3208-9bb2-468f-9f77-8b5998f4d006</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
