<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_backup_01  MariaDB 10.3  0.18 GB</name>
   <tag></tag>
   <elementGuidId>e929d964-1336-4fcc-a4fb-f05c0d757df2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.el-radio.w-100.h-100.mx-0.p-m.border-radius-2xs.is-bordered.is-checked.label-xs.hide-checker</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pane-backup']/div/div[2]/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>4cde98e7-d6ee-499b-b8b2-d491ab3c1b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>395416c8-45ab-4eaa-b8e6-dd8f28a04d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>35285a9f-4ca5-48ee-b0c1-0bc7327f8d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>78275167-448a-4cc2-b218-f8fdbb296d1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-radio w-100 h-100 mx-0 p-m border-radius-2xs is-bordered is-checked label-xs hide-checker</value>
      <webElementGuid>d080c698-d0f7-4699-b9a6-aa1488ceed4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>labelsize</name>
      <type>Main</type>
      <value>xs</value>
      <webElementGuid>91ab16f3-5b31-4103-bec0-3389dfb7ddc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> backup_01  MariaDB 10.3 | 0.18 GB </value>
      <webElementGuid>2593c6cc-236d-4341-88b8-23769e856cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pane-backup&quot;)/div[@class=&quot;choose-instance-backup&quot;]/div[@class=&quot;el-radio-group w-100&quot;]/div[@class=&quot;-mt-xs flex-wrap el-row el-row--flex&quot;]/div[@class=&quot;mt-xs el-col el-col-8 el-col-offset-0 el-col-pull-0 el-col-push-0  el-col-tablet-24 el-col-large-tablet-12&quot;]/label[@class=&quot;el-radio w-100 h-100 mx-0 p-m border-radius-2xs is-bordered is-checked label-xs hide-checker&quot;]</value>
      <webElementGuid>cc6fbaa7-9626-4a8f-b50b-b5a9a2cc8978</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pane-backup']/div/div[2]/div/div/label</value>
      <webElementGuid>8d78b006-f7f6-487c-bf9d-ebe33b2f32bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='của 1'])[1]/following::label[1]</value>
      <webElementGuid>4d2876c5-8c44-4074-8845-219ab969416c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chọn phiên bản'])[4]/following::label[1]</value>
      <webElementGuid>5dbe8bb0-e1d5-4c9d-8042-b6e1dcecda3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>c6e77bd3-5c72-4e56-a867-10cd5133bd34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = ' backup_01  MariaDB 10.3 | 0.18 GB ' or . = ' backup_01  MariaDB 10.3 | 0.18 GB ')]</value>
      <webElementGuid>d667397d-4646-42f4-8644-f85fd7b3d2bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
