<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Nodes</name>
   <tag></tag>
   <elementGuidId>bfea0b96-0ac1-4207-9072-e6adfb09f2dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='dropdown-menu-2566']/li[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>22a8fd3a-94c8-448c-a964-127bf13caf18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nodes</value>
      <webElementGuid>b02fe199-01f0-4513-8d48-7f9f3c5ef788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdown-menu-2566&quot;)/li[@class=&quot;el-dropdown-menu__item bf-dropdown-item&quot;]/span[1]</value>
      <webElementGuid>3d4fafeb-f825-48c2-95f1-befcecdb9bf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='dropdown-menu-2566']/li[3]/span</value>
      <webElementGuid>e61c73dc-0748-41f2-a0da-b37ad3a5f882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Backups'])[5]/following::span[1]</value>
      <webElementGuid>ec384eb6-7924-4086-917b-b0c3bd190e19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tổng quan'])[4]/following::span[2]</value>
      <webElementGuid>5a710b13-7c92-4610-bbff-d8c3c5045178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cài đặt'])[4]/preceding::span[1]</value>
      <webElementGuid>0f3fddf0-cb22-4781-9ba6-47bafbac62e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xóa'])[4]/preceding::span[2]</value>
      <webElementGuid>a81ca3e3-bf95-41b5-b98b-7b67c544ab2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/ul/li[3]/span</value>
      <webElementGuid>73bcaeb6-f982-427a-a641-cc92383106f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Nodes' or . = 'Nodes')]</value>
      <webElementGuid>dd3d6d6e-ab6a-4ff9-a125-9c7e3ef0614a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
